name: Debugging with tmate

on: [push]

jobs:

  build:

    runs-on: windows-latest

    steps:

    - name: Install Haskell
      uses: input-output-hk/setup-haskell@v1
      id: setup-haskell
      with:
        ghc-version: "9.2.8"
        cabal-version: "3.10.1.0"
        pacman-packages: >
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-libsodium
          mingw-w64-x86_64-openssl
          mingw-w64-x86_64-lmdb
          base-devel
          autoconf-wrapper
          autoconf
          automake
          libtool
          make

    - uses: actions/checkout@v3

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 30
      with:
        limit-access-to-actor: true
